### ISSUE TITLE
Unused parameter n in numpy.from_generator

### ISSUE THREAD

**Issue by SimonKoop** [hristo-vrigazov/mmap.ninja#12]
It seems like the parameter `n`, total number of samples, in `mmap_ninja.numpy.from_generator` isn't actually used. Removing it would make it easier to store an a priori unknown number of samples of the same shape.

**Comment by hristo-vrigazov** [comment]
Thanks for the issue! This is a leftover from the previous generator. We'll remove this and update you here!

**Comment by hristo-vrigazov** [comment]
The `n` parameter is now removed in `v0.6.4`:

http://microlib.org/mmap_ninja/#create-a-numpy-memmap-from-a-generator

Thanks once again for the issue!
