### ISSUE TITLE
Access to Collab Notebooks

### ISSUE THREAD

**Issue by rfalcon100** [hristo-vrigazov/mmap.ninja#14]
Can you add the source for the Collab notebooks to the repo? I dont have access to Collabs inside my network so I can look at the examples.

**Comment by hristo-vrigazov** [comment]
Hi, yes, I will add them in the next few days :)

In the mean time, you can check the microlib docs:

https://microlib.org/mmap_ninja.html

**Comment by hristo-vrigazov** [comment]
@rfalcon100 There you go: https://github.com/hristo-vrigazov/mmap.ninja/tree/master/examples

**Comment by rfalcon100** [comment]
Thanks!
